select
    contact_id,
    account_id,
    first_name,
    last_name,
    first_name || ' ' || last_name as full_name,
    email,
    phone,
    mobile_phone,
    mailing_state,
    mailing_city,
    mailing_zip,
    date_of_birth,
    ssn_last_four,
    employment_status,
    employer_name,
    occupation,
    risk_tolerance,
    investment_experience,
    is_primary_contact,
    created_date,
    last_modified_date
from {{ source('salesforce_fsc', 'contact') }}
