select
    financial_account_id,
    account_id,
    contact_id,
    financial_account_name,
    financial_account_number,
    account_type,
    registration_type,
    custodian_name,
    status,
    balance,
    inception_date,
    close_date,
    model_portfolio,
    management_fee_rate,
    is_discretionary,
    created_date,
    last_modified_date
from {{ source('salesforce_fsc', 'financial_account') }}
