select
    record_pk,
    holding_id,
    account_number,
    portfolio_id,
    as_of_date,
    security_id,
    ticker,
    cusip,
    security_description,
    asset_class,
    sector,
    quantity,
    market_value,
    cost_basis,
    unrealized_gain_loss,
    weight_pct,
    change_key
from {{ ref('raw_portfolio_holdings') }}
