select
    account_id as client_key,
    account_id,
    account_name,
    account_type,
    client_segment,
    service_model,
    primary_contact_name,
    primary_contact_email,
    risk_tolerance,
    investment_experience,
    billing_state,
    billing_city,
    billing_zip,
    advisor_id,
    advisor_name,
    team_id,
    team_name,
    region,
    aum,
    relationship_start_date,
    is_active,
    created_date,
    last_modified_date
from {{ ref('slv_client') }}
