select
    {{ generate_pk(['resolved_ticker']) }} as security_key,
    security_id,
    resolved_ticker as ticker,
    resolved_cusip as cusip,
    isin,
    resolved_security_name as security_name,
    asset_class,
    sub_asset_class,
    sector,
    security_type,
    exchange,
    currency,
    issuer,
    country,
    inception_date,
    expense_ratio,
    dividend_yield,
    market_cap_category,
    is_esg,
    risk_rating,
    benchmark_index,
    security_description as description,
    is_active,
    match_status,
    resolved_at as loaded_at
from {{ ref('res_security') }}
