select
    {{ generate_pk(['client_id']) }} as client_key,
    client_id,
    client_name,
    first_name,
    last_name,
    email,
    phone,
    state,
    city,
    zip,
    account_type,
    client_segment,
    service_model,
    risk_tolerance,
    investment_experience,
    date_of_birth,
    employment_status,
    occupation,
    relationship_start_date,
    account_count,
    total_aum,
    advisor_id,
    advisor_name,
    canonical_at as loaded_at
from {{ ref('can_client') }}
