select
    financial_account_id as account_key,
    financial_account_id,
    account_number,
    financial_account_name,
    account_type,
    registration_type,
    custodian_name,
    custodian_code,
    sfdc_account_id,
    portfolio_id,
    model_id as model_portfolio_id,
    fee_schedule,
    management_fee_rate,
    is_discretionary,
    status,
    inception_date,
    date_opened,
    rep_code,
    branch_code,
    margin_approved,
    options_level,
    total_market_value,
    cash_balance,
    total_cash,
    available_to_trade
from {{ ref('slv_account_value') }}
